### ISSUE TITLE
Update Site

### ISSUE THREAD

**Issue by davidgrieser** [legacycoderocks/website#1]
Goals
1. [ ] listening to podcasts
2. [ ] joining slack
3. [ ] signing up for the newsletter or reading the archives (curated.co) 
4. [ ] attending a mastermind
5. [ ] adding to the list of awesome legacy code examples

**Comment by davidgrieser** [comment]
The first impression I get from the page makes me want to keep the chalkboard/school theme.

This might be a bit busy, but I was thinking maybe we should do a SPA (Single Page App) Design and load each section as a layer.

The chat popup, calendar, podcast player, would look like chalk markup on the image itself.

The moleskine or spiral notebook would open up to view them like notes.

![page_idea](https://cloud.githubusercontent.com/assets/292375/18147300/a37c0fee-6f99-11e6-8b10-030b31fc2f93.png)

**Comment by kamilogorek** [comment]
It could work just fine if we'd be creating a desktop-only app, however, I have a feeling that it won't look and work as we'd like to on mobile. And using RWD with so many moving parts is very error-prone.

Also, we cannot rely on a having an access to streaming of all podcasts, as some of them are hosted elsewhere (eg. http://www.hanselminutes.com/539/learning-to-love-legacy-code-with-andrea-goulet-from-corgibytes) and iTunes doesn't provide external streaming API as well (we'd have to utilize http://legacycoderocks.libsyn.com/).

I think that the safest bet for now, is creating the most informational site possible with optional fancy widgets like calendar or player. Something common like sections with image/text on the opposit sides could work.

```
| M A I N |
| ....... |
| XXX ... |
| XXX ... |
| ....... |
| ... XXX |
| ... XXX |
| XXX ... |
| XXX ... |
| ....... |
```
